export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export const SAVE_TRANSACTION_SUCCESS = 'SAVE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTIONS_SUCCESS = 'UPDATE_TRANSACTIONS_SUCCESS';
